[+] Added verification for presence of libglep.a

diff --git a/.github/workflows/ci_for_c-cpp.yml b/.github/workflows/ci_for_c-cpp.yml
--- a/.github/workflows/ci_for_c-cpp.yml
+++ b/.github/workflows/ci_for_c-cpp.yml
@@ -63,4 +63,8 @@ jobs:
                 sudo apt install libglfw3-dev
                 sudo apt install libglm-dev
 
-                make
+                # Check if the .a file was created
+                if [[ ! -f libglep.a ]]; then
+                    echo "libglep.a not found"
+                    exit 1
+                fi
